- name: user configuration
  hosts: user
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: Delete app directory
    ansible.builtin.file:
      name: /app
      state: absent

  - name: create a directory for project
    ansible.builtin.file:
      name: /app
      state: directory

  - name: delete user zip
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: downloading the application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unziping the application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: installing npm dependecies
    community.general.npm:
      path: /app

  - name: copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: start user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
